### Tensorflow sessions:

Remember in tensorflow graph definition is separated from execution. 
We need to create a session to execute any computation

In [2]:
import tensorflow as tf

In [3]:
a = tf.constant(2)
b = tf.constant(3)
c= tf.add(a,b)
d = tf.add(c,a)

Session object has a method called run whose first argument is called as fetches. It takes a list of tensors and computes it for us.

In [4]:
with tf.Session() as sess:
    print sess.run(d)

7


In [5]:
with tf.Session() as sess:
    print sess.run([c,d])

[5, 7]


In [6]:
with tf.Session() as sess:
    result = sess.run(c)

 while a,b,c,d are tensors, lets check what sess.run returns.

In [8]:
type(result)

numpy.int32

In [9]:
type(c)

tensorflow.python.framework.ops.Tensor

In [10]:
a = tf.constant(2,name="a")
b = tf.constant(3,name="b")
c = tf.add(a,b,name="c")
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs',sess.graph)
    result = sess.run(c)
    print result
writer.close() 

5


## Head to the terminal and execute 
tensorboard --logdir=./graphs

Get to the URL tensorboard mentions

# Tensorflow constants

In [12]:
a = tf.constant([2, 2], name="vector")
b = tf.constant([[0, 1], [2, 3]], name="b")

In [13]:
with tf.Session() as sess:
    print sess.run([a,b])

[array([2, 2], dtype=int32), array([[0, 1],
       [2, 3]], dtype=int32)]


In [14]:
print a

Tensor("vector:0", shape=(2,), dtype=int32)


In [15]:
print b

Tensor("b_1:0", shape=(2, 2), dtype=int32)


In [16]:
zz = tf.zeros([2, 3], tf.int32)
ones = tf.ones([2, 3], tf.int32)

In [17]:
with tf.Session() as sess:
    print sess.run([zz,ones])

[array([[0, 0, 0],
       [0, 0, 0]], dtype=int32), array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)]


In [18]:
filled = tf.fill([2,2],100)
with tf.Session() as sess:
    print sess.run(filled)

[[100 100]
 [100 100]]


In [19]:
# We can also create sequences that are constants

In [20]:
lin_space = tf.linspace(1.0, 60.0,100, name="linspace")
range_ex = tf.range(0,100,10,name = "tens")

with tf.Session() as sess:
    print sess.run([lin_space])

[array([  1.        ,   1.59595966,   2.19191933,   2.78787875,
         3.38383842,   3.97979808,   4.5757575 ,   5.17171717,
         5.76767683,   6.36363649,   6.95959616,   7.55555582,
         8.15151501,   8.74747467,   9.34343433,   9.939394  ,
        10.53535366,  11.13131332,  11.72727299,  12.32323265,
        12.91919231,  13.51515198,  14.11111164,  14.7070713 ,
        15.30303001,  15.89898968,  16.49494934,  17.09090996,
        17.68686867,  18.28282928,  18.87878799,  19.47474861,
        20.07070732,  20.66666603,  21.26262665,  21.85858536,
        22.45454597,  23.05050468,  23.6464653 ,  24.24242401,
        24.83838463,  25.43434334,  26.03030396,  26.62626266,
        27.22222328,  27.81818199,  28.41414261,  29.01010132,
        29.60606003,  30.20202065,  30.79797935,  31.39393997,
        31.98989868,  32.58586121,  33.18181992,  33.77777863,
        34.37373734,  34.96969604,  35.56565857,  36.16161728,
        36.75757599,  37.3535347 ,  37.94949722,  38.5

In [21]:
with tf.Session() as sess:
    print range_ex.eval()

[ 0 10 20 30 40 50 60 70 80 90]


In [22]:
# Create a tensor of shape [2, 3] consisting of random normal values, with mean
# -1 and standard deviation 4.
norm = tf.random_normal([2, 3], mean=-1, stddev=4)
with tf.Session() as sess:
    print sess.run(norm)

[[-1.82984781  0.35292685  5.41922522]
 [-8.85805321  4.7666378   0.60201108]]


In [23]:
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)
with tf.Session() as sess:
    print sess.run(shuff)

[[5 6]
 [1 2]
 [3 4]]


In [24]:
a = tf.constant(2)
b = tf.constant(3)
c= tf.add(a,b)
d = tf.add(c,a)

In [25]:
print tf.get_default_graph().as_graph_def()

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_1"
  op: "Add"
  input: "Add"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
      

In [26]:
a = tf.Variable(2, name="scalar")
b = tf.Variable([2, 3], name="vector")
c = tf.Variable([[0, 1], [2, 3]], name="matrix")

In [27]:
with tf.Session() as sess:
    print sess.run([a,b,c])

FailedPreconditionError: Attempting to use uninitialized value matrix
	 [[Node: _send_matrix_0 = _Send[T=DT_INT32, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=2043247266447840631, tensor_name="matrix:0", _device="/job:localhost/replica:0/task:0/cpu:0"](matrix)]]

In [28]:
# We have to initialise variables before using them.
init = tf.global_variables_initializer()
with tf.Session() as sess:
    print sess.run(init)
    print sess.run([a,b,c])

None
[2, array([2, 3], dtype=int32), array([[0, 1],
       [2, 3]], dtype=int32)]


In [29]:
# create variable W as 784 x 10 tensor, filled with zeros
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print W

<tf.Variable 'Variable:0' shape=(784, 10) dtype=float32_ref>


In [30]:
# W is a random 700 x 100 variable object
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.value()

Tensor("Variable_1/read:0", shape=(700, 10), dtype=float32)


In [31]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.eval() # >> 10

10


In [32]:
W = tf.Variable(10)
assign_op = W.assign_add(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print W.eval() 

110


In [33]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(W.initializer)
sess2.run(W.initializer)
print sess1.run(W.assign_add(10)) 
print sess2.run(W.assign_sub(2)) 
print sess1.run(W.assign_add(100)) 
print sess2.run(W.assign_sub(50)) 
sess1.close()
sess2.close()

20
8
120
-42


In [34]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])
# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)
# use the placeholder as you would a constant or a variable
c = a + b # Short for tf.add(a, b)
#If we try to fetch c, we will run into error.
with tf.Session() as sess:
    print(sess.run(c))

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'Placeholder', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 498, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/peerlessdeepaks/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-bacfb3e12db7>", line 2, in <module>
    a = tf.placeholder(tf.float32, shape=[3])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1507, in placeholder
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1997, in _placeholder
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


In [35]:
with tf.Session() as sess:
    # feed [1, 2, 3] to placeholder a via the dict {a: [1, 2, 3]}
    # fetch value of c
    print(sess.run(c, {a: [1, 2, 3]}))

[ 6.  7.  8.]
